version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "bundler"
    directory: "/gemfiles/postgresql"
    schedule:
      interval: "daily"
  - package-ecosystem: "bundler"
    directory: "/gemfiles/sqlite"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
