version: 2
updates:
  - package-ecosystem: "bundler"
    directories:
      - "/"
      - "/gemfiles/mysql-ar7"
      - "/gemfiles/mysql-ar8"
      - "/gemfiles/postgresql-ar7"
      - "/gemfiles/postgresql-ar8"
      - "/gemfiles/sqlite-ar7"
      - "/gemfiles/sqlite-ar8"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
