name: Main

on:
- push
- pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get -yqq install libpq-dev libsqlite3-dev
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Lint
      run: bundle exec rake stree:check
  mysql:
    name: MySQL
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gemfile:
          - gemfiles/mysql-ar7/Gemfile
          - gemfiles/mysql-ar8/Gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: mysql2://root:password@127.0.0.1:3306/test
      RAILS_ENV: test
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Test
      run: bundle exec rake test
  postgresql:
    name: PostgreSQL
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gemfile:
          - gemfiles/postgresql-ar7/Gemfile
          - gemfiles/postgresql-ar8/Gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: postgres://postgres:@localhost:5432/postgres
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:11.5
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - run: sudo apt-get -yqq install libpq-dev
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Test
      run: bundle exec rake test
  sqlite:
    name: SQLite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gemfile:
          - gemfiles/sqlite-ar7/Gemfile
          - gemfiles/sqlite-ar8/Gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: "sqlite3::memory:"
      RAILS_ENV: test
    steps:
    - run: sudo apt-get -yqq install libsqlite3-dev
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Test
      run: bundle exec rake test
